# Generated by Django 5.2.3 on 2025-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('grupo_interprete', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('idioma', models.CharField(max_length=100)),
                ('duracion_minutos', models.FloatField()),
                ('video', models.URLField(max_length=300)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
